### ISSUE TITLE
Uncaught TypeError: Cannot read property 'classList' of null

### ISSUE THREAD

**Issue by davidbwaters** [cferdinandi/drop#38]
Hey,

When links are clicked inside the dropdown, I get an error in the console and it won't follow my links.  I noticed the 'Drop' demo page is doing the same thing when the inner links are clicked.

Everything seems to be toggling okay aside from not following links. 

Here's the testing site in question: http://macdonald.limberlogic.com/

Any ideas?

**Comment by cferdinandi** [comment]
Hey, good catch. That's a bug in my code that got introduced when I made some updates. If you need this working immediately, I would revert back to [v7.0.1](https://github.com/cferdinandi/drop/releases/tag/v7.0.1). I'll get this fixed asap.

**Comment by cferdinandi** [comment]
And fixed: https://github.com/cferdinandi/drop/pull/39

Thanks again!

**Comment by davidbwaters** [comment]
Awesome, thanks
