### ISSUE TITLE
Drop Jumbo (with Astro Navbar). Added sub-links not working in ProcessWire CMS

### ISSUE THREAD

**Issue by chrisave** [cferdinandi/drop#40]
I'm trying to use Drop Jumbo (with Astro Navbar) with ProcessWire for a project.

The static basis is:

<nav class="nav-wrap-navbar nav-collapse">                
    <a class="nav-toggle-navbar" data-nav-toggle="#nav-menu" href="#">Menu</a>
    <div class="nav-menu-navbar" id="nav-menu">
    
        <ul class="nav-navbar">
        
            <li class="dropdown-jumbo" data-dropdown>
                <a href="FALLBACK-URL.com">
                    Link
                    <span class="dropdown-show">+</span>
                    <span class="dropdown-hide">-</span>
                </a>
                <div class="dropdown-menu-jumbo" data-dropdown-menu>
                    <div class="container">
                        <div class="grid-three-fourths float-center">                                    
                            <ul>
                                <li><a href="#">Sub-link</a></li>                                    
                            </ul>  
                        </div>                                  
                    </div>
                </div>
            </li>
                 
        </ul>
        
    </div>
</nav>

So, I've replaced divs and texts (only) with an ul, lists and anchors (if compared to the demo).

Perhaps because of this (an active class being applied to a second-level anchor(?)) or something else, when I click on a sub-link in the drop-down menu, it doesn't load the page targeted by the anchor/link (but the URL is fine).
There is the following message in Firebug's Console(?):
"TypeError: i is null

...e.classList.toggle(o.toggleActiveClass),i.classList.toggle(o.contentActiveClass)..."

The fallback URL is the first sub-link URL.

**Comment by cferdinandi** [comment]
So this is a bug in 9.2.0. Please upgrade to 9.2.1 and the problem will go away. Sorry!

https://github.com/cferdinandi/drop/releases/tag/v9.2.1

**Comment by chrisave** [comment]
Thank you for fixing it.
Have a nice day :)!

Christophe

2015-09-16 16:37 GMT+02:00 Chris Ferdinandi <notifications@github.com>:
